apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-tutorial
spec:
  selector:
    matchLabels:
      app: gitops-tutorial
  replicas: 2
  template:
    metadata:
      labels:
        app: gitops-tutorial
    spec:
      containers:
      - name: gitops-tutorial
        image: elastic2ls/gitops-tutorial:build-24
        ports:
        - containerPort: 80
